name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:

  release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v3.1
        with:
          java-version: adopt@1.8

      - name: Release
        run: >-
          sbt
          -J-Xmx3G
          -J-XX:+UseG1GC
          -DCI=1
          ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
